configs:
  cm:
    url: "https://cd.cucumber.alleaffengaffen.ch"
    server.rbac.log.enforce.enable: "true"
    exec.enabled: "true"
    admin.enabled: "true"
  rbac:
    policy.default: role:readonly

server:
  replicas: 2
  pdb:
    minAvailable: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: Equals
                    value: server
                  - key: app.kubernetes.io/name
                    operator: Equals
                    value: argocd-server
              topologyKey: topology.kubernetes.io/zone
  topologySpreadConstraints:
    - maxSkew: 0
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  ingress:
    enabled: true
    annotations: {}
    ingressClassName: "cilium"
    hosts:
      - cd.cucumber.alleaffengaffen.ch
  priorityClassName: "system-cluster-critical"
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

  controller:
    enableStatefulSet: true
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 128Mi

  notifications:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  redis:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 16Mi
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  repoServer:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  applicationSet:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
