## CNI Chaining values
# enableIPv4Masquerade: false
# tunnel: disabled
# endpointRoutes:
#   enabled: false
# cni:
#   chainingMode: aws-cni

## AWS ENI ipam values
# eni:
#   enabled: true
# ipam:
#   mode: eni
# egressMasqueradeInterfaces: eth0
# tunnel: disabled

## General values
kubeProxyReplacement: "strict"
k8sServiceHost: ${API_SERVER_IP}
k8sServicePort: ${API_SERVER_PORT}
debug:
  enabled: true
cluster:
  name: cucumber
rollOutCiliumPods: true
priorityClassName: "system-node-critical"
annotateK8sNode: true
policyEnforcementMode: "never"
ingressController:
  enabled: true
  enforceHttps: true
containerRuntime:
  integration: containerd
  socketPath: /var/run/containerd/containerd.sock

## Resources and security-contexts
operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
hubble:
  enabled: true
  rollOutPods: true
  relay:
    enabled: true
    rollOutPods: true
    resources:
      limits:
        cpu: 1000m
        memory: 1024M
      requests:
        cpu: 100m
        memory: 64Mi
  ui:
    enabled: true
    rollOutPods: true
    securityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    backend:
      resources:
        limits:
          cpu: 1000m
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
    frontend:
      resources:
        limits:
          cpu: 1000m
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
    proxy:
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 24Mi
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 300Mi
